# Generated by Django 3.2.8 on 2021-10-27 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_book_languages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='languages',
            new_name='language',
        ),
    ]
